# Generated by Django 3.2.25 on 2024-07-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240702_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoria'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.proveedor'),
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('orden_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ordencompra')),
                ('productos', models.ManyToManyField(null=True, related_name='remisiones', to='main.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, unique=True)),
                ('fecha_recibido', models.DateField(null=True)),
                ('fecha_pago', models.DateField(null=True)),
                ('pagado', models.BooleanField(default=False, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('productos', models.ManyToManyField(null=True, related_name='facturas', to='main.Inventario')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.proveedor')),
            ],
        ),
    ]
